name: Daily Standup Bot
on:
  schedule:
    - cron: "15 9 * * *" #"0 9 * * *" "46 8 * * *"# Runs at 9 AM UTC daily(2:30 PM IST)
  workflow_dispatch:       # allows manual run from Actions tab

jobs:
  standup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run DailySync
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          REPO_OWNER: ${{ secrets.REPO_OWNER }}
          REPO_NAME: ${{ secrets.REPO_NAME }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
        run: python main.py